# One value per line to exclude completely
# Lines starting with # are comments
# Example:
# xn--example-domain-123.com
xn--iphignie-f1a.com # https://www.iphigen.ie/
xn--socit-esab.com # https://www.societe.com/
xn--sjldnesygdomme-1ib.dk # https://www.sjoldnesygdomme.dk/
xn--sanofiaventis-gm6g.com # global‐is‐quality‐portal.sanofi‐aventis.com
franais # français without the cedilla
sanofiaventis
www.xn--atelierdelaneurodiversit-yfc.fr
www.xn--location-vlo-annecy-kzb.fr
xn--comsafpharmacovigilancematriovigilance-0md
www.xn--abri-franais-sdb.fr
xn--sanofijasin-v8a.fi #sanofijasinä.fi
фондкругдобра.рф # State foundation “Circle of Kindness” (Krug Dobra). Its main purpose is to help children with severe and rare (orphan) diseases.
xn--8ca # è
xn--clabousse-93a # éclabousse
xn--srvr-5nac # sárvár
whois.nic.xn--55qx5d # whois.nic.公司

xn--80abfdb8athfre5ah.xn--p1ai # фондкругдобра.рф
xn--80ajghhoc2aj1c8b.xn--p1ai # честныйзнак.рф
xn----7sbbumkojddmeoc1a7r.xn--p1acf # компания-партнер.рус
xn-----6kcaclhfbjeaoqgujpbi0dm6apzih4j2h7b.xn--p1ai # запчасти-для-электродвигателей.рф
xn----8sbhtdkcsfcivgoh1b.xn--p1ai # хостинг-картинок.рф
xn----7sbbgbqdoegn8bhyq4u.xn--p1ai # красивое-вязание.рф
xn----8sbxbebcd4a9ai.xn--p1ai # о-китайский.рф
xn--80afnfom.xn--80ahmohdapg.xn--80asehdb # мойгаз.смородина.онлайн
xn--q1ac.xn--b1abqffracbogz7j.xn--p1ai # ст.корольговорит.рф